### ISSUE TITLE
Thanks for great work

### ISSUE THREAD

**Issue by zewelor** [davidkrantz/Colorfy#1]
Hi

Just want to thank you for this great project. It works wonderful. 
I've played with k values for kmeans clusters count, and for my 4 works better. I've changed implementation from sklearn to scipy for less dependencies, so maybe thats the difference. Also I've extracted logic and put it inside Home Assistant custom component ( https://community.home-assistant.io/t/change-your-rgb-lights-color-according-to-spotify-album-background/94885 ), added link in code comment. I hope that's ok. Thanks again for great project !

**Comment by davidkrantz** [comment]
Hello,

Thank you! Changing the dependency from sklearn to scipy is a great idea which I also will try out. I am all good with the Home Assistant component, I am happy that the code come into use!

**Comment by davidkrantz** [comment]
Closing since it's not really an issue!
