### ISSUE TITLE
Error runing main.py

### ISSUE THREAD

**Issue by santanafabio** [davidkrantz/Colorfy#2]
Gdk-CRITICAL **: 21:19:07.749: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

after do all the following instructions, I'm getting this error when I run the:
$ sudo python3 main.py -k 8 -t 10 -s 100 100

Any guess?

**Comment by davidkrantz** [comment]
This looks like a problem with your `matplotlib` backend. Try to add `matplotlib.use('Agg')` below the `import matplotlib` statement in `spotify_background_color.py`. If it still does not work you can try to delete all the code used for plotting and see if it helps.

**Comment by santanafabio** [comment]
Looks like this worked to keep going, but now I'm getting 2 errors:
```
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
current_spotify_playback.CouldNotRefreshTokenException: Could not refresh token.
```
And I'm not handling to create a new refresh token.
Any ideas?

**Comment by davidkrantz** [comment]
Great! Couple of things:

- Could you specify at what line and file the first error occurs?
- What do you mean with "And I'm not handling to create a new refresh token"? If you haven't specified a refresh token then it is not weird that you got `CouldNotRefreshTokenException`
- Have you followed the guide and done every step?

**Comment by pawKer** [comment]
> Looks like this worked to keep going, but now I'm getting 2 errors:
> 
> ```
> TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
> current_spotify_playback.CouldNotRefreshTokenException: Could not refresh token.
> ```
> 
> And I'm not handling to create a new refresh token.
> Any ideas?

It looks like your REFRESH_TOKEN is None. 
>TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

Maybe `os.environ.get('SPOTIPY_REFRESH_TOKEN')` is not getting the correct value. Try  hardcoding it to a value in `main.py` and see if you still get the error.

**Comment by davidkrantz** [comment]
Closed due to inactivity. Reopen if the problem remains.
