### ISSUE TITLE
sp.imresize is deprecated in newer scipy versions

### ISSUE THREAD

**Issue by pawKer** [davidkrantz/Colorfy#6]
https://github.com/davidkrantz/Colorfy/blob/1bc96dc4ce619dcc6df6ed2be6d88c7fc1947e9e/spotify_background_color.py#L44-L45

Instead, something like this could be done.

`im = Image.fromarray(self.img, 'RGB')` 
`self.img = np.asarray( im.resize((image_processing_size, image_processing_size)), dtype="int32" )`

**Comment by davidkrantz** [comment]
This is now [fixed](https://github.com/davidkrantz/Colorfy/commit/69e8573840df6ac9090f346256157015166620cb). Changed from SciPy to Pillow as you proposed since the latter is already used in another file.
