### ISSUE TITLE
licence?

### ISSUE THREAD

**Issue by nickw444** [davidkrantz/Colorfy#7]
Hi David, 

Thank you for publishing this code. However, I wish to slightly adapt `spotify_background_color.py` into my own use-case (for use with AppDaemon in Home-Assistant). 

I noticed there was no `LICENSE` file in the root, so I would like to clarify if the code is available under an MIT (or similar) license so I can re-purpose it for my use-case for my smart home?

**Comment by davidkrantz** [comment]
Hello,

Thank you for pointing out that the repo did not have a license. I have now licensed it using a MIT license, so you are free to use the code under those conditions 😄

**Comment by nickw444** [comment]
Thanks!
