### ISSUE TITLE
Inconsistent variable name

### ISSUE THREAD

**Issue by matecomp** [davidkrantz/Colorfy#8]
Great job with this project, I be using it for understanding the spotify method to define the background color. Thanks!!

Reading your code, I believe that you wanted define this variable name as **rg_mean, rg_std** and not **rb_mean, rb_std**, right?
https://github.com/davidkrantz/Colorfy/blob/c59ad1547d4f7327a3eba5051cce6a807c07c9b7/spotify_background_color.py#L161

**Comment by davidkrantz** [comment]
Hi,

You are absolutely right, nice found! This is now [fixed](https://github.com/davidkrantz/Colorfy/commit/69e8573840df6ac9090f346256157015166620cb) 🎉
